version: '3.8'
services:
  babyguard:
    image: "zedstron/babyguard:latest"
    build:
      context: ../src
      dockerfile: ./Dockerfile
    platform: linux/arm64
    privileged: true
    network_mode: host
    devices:
      - /dev/snd
      - /dev/video0
      - /dev/gpiomem
      - /dev/mem
      - /dev/lirc0
    group_add:
      - audio
    container_name: babyguard
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ../media:/app/media
      - ../cert:/app/cert
      - ../assets:/app/assets
    env_file:
      - ../.env